- id: ruff
  name: ruff
  description: "Run 'ruff' with default config"
  entry: ruff --config  ./pyproject.toml
  language: python
  types_or: [python]
  args: []
  require_serial: true
  minimum_pre_commit_version: "2.9.2"
